---
title: '**Observatório de Pessoal:** identidade visual em Rmarkdown'
output:
  html_document:
    toc: true
    df_print: paged
  word_document: 
    toc: true
    reference_docx: auxiliares/model_ref3_edit.docx
lang: pt-BR
toc-title: 'Índice'
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r globals, include = F}
library(data.table)
library(dplyr)
library(rmarkdown)
library(flextable)
library(ggplot2)
library(DT)
library(plotly)
library(crosstalk)
# source("auxiliares/metodos.R")


### TESTE DE COMMIT NA ORGANIZATION (WESLEY)
```


```{r setup, include=FALSE}
### opções de tamanhos das figuras
fw <- 12
fh <- 6

### opções de chunk
knitr::opts_chunk$set(list(warning = FALSE,
                           message = FALSE,
                           echo = FALSE,
                           fig.width = fw,
                           fig.height = fh,
                           dev = c('png','pdf','svg'),
                           fig.path = "idt_visual/",
                           fig.ext = c("png","pdf",'svg')
                           )
                      )



### opções de tamanhos de texto dos itens (eixo, legendas, etc)
txt_size <- 15

### opção de tamanho de texto no label (geom_text)
txt_geom_size <- 5

# paleta de cores para variáveis categóricas
# plt_dn1i_cat <- "Paired"
pal_primaria <- c('#0000AA',
                  ponto = '#FF7800',
                  principal = '#00A100')# COR PRINCIPAL


pal_complementar <- c(pal_primaria,
                      '#FFCE08',
                      '#EE3A79',
                      '#37C2D5',
                      '#C13C01',
                      '#9B83D9')


update_geom_defaults("col",list(fill = pal_primaria["principal"]))
update_geom_defaults("line",list(colour = pal_primaria["principal"]))
update_geom_defaults('smooth',list(colour = pal_primaria["principal"]))
update_geom_defaults("boxplot",list(fill = pal_primaria["principal"],
                                    col = pal_primaria["ponto"]))
update_geom_defaults("point",list(colour = pal_primaria["ponto"]))

# cores para categóricas, 'fill' e 'color'
plot_fill_cat <- scale_fill_discrete(palette = pal_complementar) 
plot_color_cat <- scale_color_discrete(palette = pal_complementar) 

# cores para contínuas, 'fill' e 'color'
plot_fill_cont <- scale_fill_gradient(low = '#006401',
                                      high = '#CDFFCC')

plot_color_cont <- scale_colour_gradient(low = '#006401',
                                         high = '#CDFFCC')

# configurações de tema e legenda
plot_config <- 
  theme_minimal() +
  theme(text = element_text(size = txt_size),
        legend.position = "bottom",
        legend.direction = "horizontal")


# 'NOVO' ggplot para escala de cores categóricas
ggplot_cat <- function(...){
  ggplot(...) +
    plot_fill_cat + 
    plot_color_cat + 
    plot_config
}


# 'NOVO' ggplot para escala de cores contínuoas
ggplot_cont <- function(...){
  ggplot(...) +
    plot_fill_cont + 
    plot_color_cont 
}


# 'NOVO' ggplot que detecta automaticamente o tipo de escla
ggplot_new <- function(...){
  
  # 1. Abrimos um dispositivo gráfico "fantasma" que não abre janela no Windows/Mac/Linux
  pdf(NULL) 
  
  # Usamos o on.exit para garantir que o dispositivo feche, não importa o que aconteça
  on.exit(if (!is.null(dev.list())) dev.off())
  
  # p <- ggplot(...)
  
  p_out <- 
    tryCatch({
      p1 <- ggplot_cat(...)
      print(p1)
      return(p1)
      },
      error = function(e){
        p2 <- ggplot_cont(...)
        return(p2)
        }
    )
  
  return(p_out)
  }




# função para contar figura
fig_id <- 0
num_fig <- function(title){
  fig_id <<- fig_id + 1
  txt <- paste0("\n\n###### Figura ",fig_id," - ",title,"\n\n")
  cat(txt)
  }

# função para contar tabela
tb_id <- 0
num_tb <- function(title){
  tb_id <<- tb_id + 1
  txt <- paste0("\n\n###### Tabela ",tb_id," - ",title,"\n\n")
  cat(txt)
}


```


## Pontos e linhas

You can also embed plots, for example:

```{r ponto_linha}
ggplot_new(pressure,aes(x = temperature,y = pressure)) +
  geom_line() + 
  geom_point()
```

## Pontos e linha de 'smooth'

```{r linha_smooth, echo = T}
ggplot(mtcars,
       aes(x = hp,y = wt)) + 
  geom_point() + 
  geom_smooth() -> plot_ex1
plot_ex1
```

## Pontos e linha de 'smooth' usando plotly

```{r linha_smooth_plotly,echo = T}
ggplotly(plot_ex1)
```


```{r linha_smooth2, echo = T}
ggplot_cont(mtcars,
           aes(x = hp,y = wt)) + 
  geom_point() + 
  geom_smooth() 
```

## Cor e preenchimento de categorias

```{r preenchimento_cat}
ggplot_new(mtcars,
           aes(x = hp,y = wt,col = as.factor(carb))) + 
  geom_point(size = 5)

mtcars %>% setDT %>% .[,.N,.(carb = as.character(carb))] %>%
  ggplot_new(aes(x = carb,y = N,fill = carb)) + 
  geom_col()
  
```


## Cor e preenchimento em gradiente


```{r preenchimento_cont}
ggplot_new(mtcars,
           aes(x = hp,y = wt,col = carb)) + 
  geom_point(size = 5)


mtcars %>% setDT %>% .[,.N,.(carb)] %>%
  ggplot_new(aes(x = carb,y = N,fill = carb))+ 
  geom_col()
  
```

## Exemplo com DataTable

```{r datatable}
mtcars %>%
  head() %>%
  DT::datatable() -> dt1
dt1
```

## Tabela-gráfico

```{r crosstalk1, echo = T}
bscols(ggplotly(plot_ex1),
       dt1,
       widths = c(6,6),
       device = "sm")
```


## Tabela-tabela

```{r crosstalk2, echo = T}
bscols(dt1,
       dt1,
       widths = c(6,6),
       device = "sm")
```
